//
//  TestConfigurator.swift
//  TestApp
//
//  Created by Jakub Hutny on 19.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension TestViewController: TestPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension TestInteractor: TestViewControllerOutput
{
}

extension TestPresenter: TestInteractorOutput
{
}

class TestConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = TestConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: TestViewController)
  {
    let router = TestRouter()
    router.viewController = viewController
    
    let presenter = TestPresenter()
    presenter.output = viewController
    
    let interactor = TestInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
