//
//  TestInteractor.swift
//  TestApp
//
//  Created by Jakub Hutny on 19.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol TestInteractorInput
{
  func doSomething(request: Test.Something.Request)
}

protocol TestInteractorOutput
{
  func presentSomething(response: Test.Something.Response)
}

class TestInteractor: TestInteractorInput
{
  var output: TestInteractorOutput!
  var worker: TestWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Test.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = TestWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Test.Something.Response()
    output.presentSomething(response: response)
  }
}
